-- MySQL Script generated by MySQL Workbench
-- Mon Jan  1 20:20:30 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bluefh
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bluefh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bluefh` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `bluefh` ;

-- -----------------------------------------------------
-- Table `bluefh`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bluefh`.`accounts` (
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `active` TINYINT(1) NULL DEFAULT NULL,
  `avatar` VARCHAR(100) NULL DEFAULT NULL,
  `role` ENUM('PATIENT', 'DOCTOR', 'NURSE', 'STAFF', 'ADMIN') NOT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_date` DATETIME NOT NULL,
  `updated_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bluefh`.`administrators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bluefh`.`administrators` (
  `id` BIGINT NOT NULL,
  `inauguration_day` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `administrators_ibfk_1`
    FOREIGN KEY (`id`)
    REFERENCES `bluefh`.`employees` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bluefh`.`bills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bluefh`.`bills` (
  `medicine_money` DOUBLE NOT NULL,
  `pre_examination` DOUBLE NOT NULL,
  `total_price` DOUBLE NOT NULL,
  `examination_date` DATETIME NOT NULL,
  `cashier_id` BIGINT NOT NULL,
  `patient_id` BIGINT NOT NULL,
  `medical_bill_id` BIGINT NOT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_date` DATETIME NOT NULL,
  `updated_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `medical_bill_id` (`medical_bill_id` ASC) VISIBLE,
  INDEX `cashier_id` (`cashier_id` ASC) VISIBLE,
  INDEX `patient_id` (`patient_id` ASC) VISIBLE,
  CONSTRAINT `bills_ibfk_1`
    FOREIGN KEY (`cashier_id`)
    REFERENCES `bluefh`.`cashiers` (`id`),
  CONSTRAINT `bills_ibfk_2`
    FOREIGN KEY (`patient_id`)
    REFERENCES `bluefh`.`patients` (`id`),
  CONSTRAINT `bills_ibfk_3`
    FOREIGN KEY (`medical_bill_id`)
    REFERENCES `bluefh`.`medical_bills` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bluefh`.`cashiers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bluefh`.`cashiers` (
  `id` BIGINT NOT NULL,
  `skills` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `cashiers_ibfk_1`
    FOREIGN KEY (`id`)
    REFERENCES `bluefh`.`employees` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bluefh`.`doctors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bluefh`.`doctors` (
  `id` BIGINT NOT NULL,
  `specialist` VARCHAR(100) NOT NULL,
  `years_of_experience` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `doctors_ibfk_1`
    FOREIGN KEY (`id`)
    REFERENCES `bluefh`.`employees` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bluefh`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bluefh`.`employees` (
  `id` BIGINT NOT NULL,
  `salary` DOUBLE NOT NULL,
  `salary_coefficient` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `employees_ibfk_1`
    FOREIGN KEY (`id`)
    REFERENCES `bluefh`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bluefh`.`examination_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bluefh`.`examination_list` (
  `examination_date` DATETIME NOT NULL,
  `nurse_id` BIGINT NOT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_date` DATETIME NOT NULL,
  `updated_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `nurse_id` (`nurse_id` ASC) VISIBLE,
  CONSTRAINT `examination_list_ibfk_1`
    FOREIGN KEY (`nurse_id`)
    REFERENCES `bluefh`.`nurses` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bluefh`.`examination_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bluefh`.`examination_schedule` (
  `note` VARCHAR(100) NULL DEFAULT NULL,
  `patient_id` BIGINT NOT NULL,
  `doctor_id` BIGINT NOT NULL,
  `examination_list_id` BIGINT NOT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_date` DATETIME NOT NULL,
  `updated_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `patient_id` (`patient_id` ASC) VISIBLE,
  INDEX `doctor_id` (`doctor_id` ASC) VISIBLE,
  INDEX `examination_list_id` (`examination_list_id` ASC) VISIBLE,
  CONSTRAINT `examination_schedule_ibfk_1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `bluefh`.`patients` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `examination_schedule_ibfk_2`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `bluefh`.`doctors` (`id`),
  CONSTRAINT `examination_schedule_ibfk_3`
    FOREIGN KEY (`examination_list_id`)
    REFERENCES `bluefh`.`examination_list` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bluefh`.`medical_bills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bluefh`.`medical_bills` (
  `diagnostic` VARCHAR(100) NOT NULL,
  `symptoms` VARCHAR(100) NOT NULL,
  `examination_date` DATETIME NOT NULL,
  `patient_id` BIGINT NOT NULL,
  `doctor_id` BIGINT NOT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_date` DATETIME NOT NULL,
  `updated_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `patient_id` (`patient_id` ASC) VISIBLE,
  INDEX `doctor_id` (`doctor_id` ASC) VISIBLE,
  CONSTRAINT `medical_bills_ibfk_1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `bluefh`.`patients` (`id`),
  CONSTRAINT `medical_bills_ibfk_2`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `bluefh`.`doctors` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bluefh`.`medicalbill_packages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bluefh`.`medicalbill_packages` (
  `medical_bill_id` BIGINT NOT NULL,
  `packages_id` BIGINT NOT NULL,
  PRIMARY KEY (`medical_bill_id`, `packages_id`),
  INDEX `packages_id` (`packages_id` ASC) VISIBLE,
  CONSTRAINT `medicalbill_packages_ibfk_1`
    FOREIGN KEY (`medical_bill_id`)
    REFERENCES `bluefh`.`medical_bills` (`id`),
  CONSTRAINT `medicalbill_packages_ibfk_2`
    FOREIGN KEY (`packages_id`)
    REFERENCES `bluefh`.`packages` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bluefh`.`medicine_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bluefh`.`medicine_type` (
  `type_of_medicine` VARCHAR(20) NOT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_date` DATETIME NOT NULL,
  `updated_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_of_medicine` (`type_of_medicine` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bluefh`.`medicine_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bluefh`.`medicine_types` (
  `medicine_id` BIGINT NOT NULL,
  `medicine_type_id` BIGINT NOT NULL,
  PRIMARY KEY (`medicine_id`, `medicine_type_id`),
  INDEX `medicine_type_id` (`medicine_type_id` ASC) VISIBLE,
  CONSTRAINT `medicine_types_ibfk_1`
    FOREIGN KEY (`medicine_id`)
    REFERENCES `bluefh`.`medicines` (`id`),
  CONSTRAINT `medicine_types_ibfk_2`
    FOREIGN KEY (`medicine_type_id`)
    REFERENCES `bluefh`.`medicine_type` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bluefh`.`medicine_unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bluefh`.`medicine_unit` (
  `unit_name` VARCHAR(20) NOT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_date` DATETIME NOT NULL,
  `updated_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unit_name` (`unit_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bluefh`.`medicines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bluefh`.`medicines` (
  `medicine_name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `note` VARCHAR(100) NULL DEFAULT NULL,
  `price` DOUBLE NOT NULL,
  `amount` INT NOT NULL,
  `image` VARCHAR(100) NULL DEFAULT NULL,
  `direction_for_use` VARCHAR(100) NOT NULL,
  `medicine_unit_id` BIGINT NOT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_date` DATETIME NOT NULL,
  `updated_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `medicine_name` (`medicine_name` ASC) VISIBLE,
  INDEX `medicine_unit_id` (`medicine_unit_id` ASC) VISIBLE,
  CONSTRAINT `medicines_ibfk_1`
    FOREIGN KEY (`medicine_unit_id`)
    REFERENCES `bluefh`.`medicine_unit` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bluefh`.`nurses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bluefh`.`nurses` (
  `id` BIGINT NOT NULL,
  `educational_attainment` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `nurses_ibfk_1`
    FOREIGN KEY (`id`)
    REFERENCES `bluefh`.`employees` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bluefh`.`packages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bluefh`.`packages` (
  `packages_name` VARCHAR(20) NOT NULL,
  `price` DOUBLE NOT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_date` DATETIME NOT NULL,
  `updated_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `packages_name` (`packages_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bluefh`.`patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bluefh`.`patients` (
  `id` BIGINT NOT NULL,
  `insurance_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `insurance_id` (`insurance_id` ASC) VISIBLE,
  CONSTRAINT `patients_ibfk_1`
    FOREIGN KEY (`id`)
    REFERENCES `bluefh`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bluefh`.`prescriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bluefh`.`prescriptions` (
  `amount` INT NOT NULL,
  `note` VARCHAR(100) NULL DEFAULT NULL,
  `medicine_id` BIGINT NOT NULL,
  `medical_bill_id` BIGINT NOT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_date` DATETIME NOT NULL,
  `updated_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `medicine_id`, `medical_bill_id`),
  INDEX `medicine_id` (`medicine_id` ASC) VISIBLE,
  INDEX `medical_bill_id` (`medical_bill_id` ASC) VISIBLE,
  CONSTRAINT `prescriptions_ibfk_1`
    FOREIGN KEY (`medicine_id`)
    REFERENCES `bluefh`.`medicines` (`id`),
  CONSTRAINT `prescriptions_ibfk_2`
    FOREIGN KEY (`medical_bill_id`)
    REFERENCES `bluefh`.`medical_bills` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bluefh`.`regulations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bluefh`.`regulations` (
  `regulation_name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `note` VARCHAR(100) NULL DEFAULT NULL,
  `status` TINYINT(1) NOT NULL,
  `admin_id` BIGINT NOT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_date` DATETIME NOT NULL,
  `updated_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `regulation_name` (`regulation_name` ASC) VISIBLE,
  INDEX `admin_id` (`admin_id` ASC) VISIBLE,
  CONSTRAINT `regulations_ibfk_1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `bluefh`.`administrators` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bluefh`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bluefh`.`users` (
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `gender` ENUM('MALE', 'FEMALE', 'OTHER') NOT NULL,
  `dob` DATETIME NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `phone_number` VARCHAR(11) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `account_id` BIGINT NOT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_date` DATETIME NOT NULL,
  `updated_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `account_id` (`account_id` ASC) VISIBLE,
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`account_id`)
    REFERENCES `bluefh`.`accounts` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
